// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiJpJhlm5_c6uAR9yo47Sw65rzSoo3rsI',
    appId: '1:27349470592:web:a5290eb62039327be48565',
    messagingSenderId: '27349470592',
    projectId: 'mydocent-ec622',
    authDomain: 'mydocent-ec622.firebaseapp.com',
    databaseURL: 'https://mydocent-ec622-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mydocent-ec622.appspot.com',
    measurementId: 'G-VEL25KVPRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSrQa6hdvMw5lncE3cURXzUxpHkDYIIqE',
    appId: '1:27349470592:android:067c6f0d71ab118ce48565',
    messagingSenderId: '27349470592',
    projectId: 'mydocent-ec622',
    databaseURL: 'https://mydocent-ec622-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mydocent-ec622.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgGQF_rSR3pukNkAnVEn53RSF-t6VNjn8',
    appId: '1:27349470592:ios:b03e8262a048f1e8e48565',
    messagingSenderId: '27349470592',
    projectId: 'mydocent-ec622',
    databaseURL: 'https://mydocent-ec622-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mydocent-ec622.appspot.com',
    iosBundleId: 'com.example.docent',
  );

}